/* Create Tables */

CREATE TABLE ADMIN
(
	AID INT NOT NULL UNIQUE,
	EMAIL VARCHAR(100),
	PASSWORD VARCHAR(100),
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	ROLE VARCHAR(50),
	PRIMARY KEY (AID)
);


CREATE TABLE ANSWER
(
	ANSID INT NOT NULL UNIQUE,
	SID INT,
	QID INT NOT NULL UNIQUE,
	FID INT NOT NULL UNIQUE,
	POINT VARCHAR(50),
	PRIMARY KEY (ANSID)
);


CREATE TABLE FACULTY
(
	FID INT NOT NULL UNIQUE,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	DEPT VARCHAR(50) NOT NULL,
	CLASS VARCHAR(50) NOT NULL,
	SUBJECT VARCHAR(50) NOT NULL,
	PRIMARY KEY (FID)
);


CREATE TABLE FEEDBACK
(
	FDID INT NOT NULL UNIQUE,
	SID INT NOT NULL UNIQUE,
	FID INT NOT NULL UNIQUE,
	COMMENT VARCHAR(200),
	PRIMARY KEY (FDID)
);


CREATE TABLE QUESTION
(
	QID INT NOT NULL UNIQUE,
	QUESTION VARCHAR(200),
	PRIMARY KEY (QID)
);


CREATE TABLE RATING
(
	RID INT NOT NULL UNIQUE,
	FID INT NOT NULL UNIQUE,
	RATE VARCHAR(50),
	PRIMARY KEY (RID)
);


CREATE TABLE STUDENT
(
	SID INT NOT NULL UNIQUE,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(0),
	ROLLNO INT NOT NULL UNIQUE,
	YEAR VARCHAR(50) NOT NULL,
	MAJOR VARCHAR(50) NOT NULL,
	PHONENO VARCHAR(50),
	PRIMARY KEY (SID)
);


CREATE TABLE SUGGESTION
(
	SUID INT NOT NULL UNIQUE,
	ADVICE VARCHAR(200),
	FID INT NOT NULL UNIQUE,
	PRIMARY KEY (SUID)
);



/* Create Foreign Keys */

ALTER TABLE ANSWER
	ADD FOREIGN KEY (FID)
	REFERENCES FACULTY (FID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FEEDBACK
	ADD FOREIGN KEY (FID)
	REFERENCES FACULTY (FID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RATING
	ADD FOREIGN KEY (FID)
	REFERENCES FACULTY (FID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SUGGESTION
	ADD FOREIGN KEY (FID)
	REFERENCES FACULTY (FID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ANSWER
	ADD FOREIGN KEY (QID)
	REFERENCES QUESTION (QID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ANSWER
	ADD FOREIGN KEY (SID)
	REFERENCES STUDENT (SID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FEEDBACK
	ADD FOREIGN KEY (SID)
	REFERENCES STUDENT (SID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



